// Generated by js_of_ocaml 3.4.0
(function(a){"use strict";var
$=" : flags Open_text and Open_binary are not compatible",N="Sys_error",_="Invalid_argument",M=0xf0,Z=0x800,Y="jsError",s=1024,X="End_of_file",i=0x80,W="Failure",K="Undefined_recursive_module",L=" : flags Open_rdonly and Open_wronly are not compatible",J="([^/]*)",I=512,V="Stack_overflow",c="",y="^",G=" : file already exists",H=0xe0,p=0x3f,F=0xdfff,U="Not_found",E="Assert_failure",n="/",x=128,R="Sys_blocked_io",S="fd ",T=0xdc00,D="Out_of_memory",Q="Match_failure",f=248,O="Division_by_zero",P="static/",az=0;function
aq(){return az++}function
aB(b,a){throw[0,b,a]}function
aC(b,a){if(a.repeat)return a.repeat(b);var
d=c,e=0;if(b==0)return d;for(;;){if(b&1)d+=a;b>>=1;if(b==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
aL(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
B(b,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==b.length)return e.apply(null,b);var
f=c;for(;0<a;d+=s,a-=s)f+=e.apply(null,aL(b,d,Math.min(a,s)));return f}function
ap(a){if(a.t==2)a.c+=aC(a.l-a.c.length,"\0");else
a.c=B(a.c,0,a.c.length);a.t=0}function
ad(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aF(f){for(var
l=c,d=c,h,g,j,a,b=0,k=f.length;b<k;b++){g=f.charCodeAt(b);if(g<i){for(var
e=b+1;e<k&&(g=f.charCodeAt(e))<i;e++);if(e-b>I){d.substr(0,1);l+=d;d=c;l+=f.slice(b,e)}else
d+=f.slice(b,e);if(e==k)break;b=e}a=1;if(++b<k&&((j=f.charCodeAt(b))&-64)==x){h=j+(g<<6);if(g<H){a=h-0x3080;if(a<i)a=1}else{a=2;if(++b<k&&((j=f.charCodeAt(b))&-64)==x){h=j+(h<<6);if(g<M){a=h-0xe2080;if(a<Z||a>=0xd7ff&&a<0xe000)a=2}else{a=3;if(++b<k&&((j=f.charCodeAt(b))&-64)==x&&g<0xf5){a=j-0x3c82080+(h<<6);if(a<0x10000||a>0x10ffff)a=3}}}}}if(a<4){b-=a;d+="\ufffd"}else
if(a>0xffff)d+=String.fromCharCode(0xd7c0+(a>>10),T+(a&0x3FF));else
d+=String.fromCharCode(a);if(d.length>s){d.substr(0,1);l+=d;d=c}}return l+d}function
aE(a){switch(a.t){case
9:return a.c;default:ap(a);case
0:if(ad(a.c)){a.t=9;return a.c}a.t=8;case
8:return aF(a.c)}}function
k(c,a,b){this.t=c;this.c=a;this.l=b}k.prototype.toString=function(){return aE(this)};k.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
k(this.t,a,this.l)};function
e(a){return new
k(0,a,a.length)}function
ag(b,a){aB(b,e(a))}var
b=[0];function
j(a){ag(b.Sys_error,a)}var
o=new
Array();function
au(e){var
a=o[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==c)return 0;if(a.fd&&b.fds[a.fd]&&b.fds[a.fd].output){var
d=b.fds[a.fd].output;switch(d.length){case
2:d(e,a.buffer);break;default:d(a.buffer)}}a.buffer=c;return 0}if(a.process&&a.process.cwd)var
t=a.process.cwd().replace(/\\/g,n);else
var
t="/static";if(t.slice(-1)!==n)t+=n;function
as(a){a=a
instanceof
k?a.toString():a;if(a.charCodeAt(0)!=47)a=t+a;var
e=a.split(n),b=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(c);break;default:b.push(e[d]);break}b.orig=a;return b}function
aA(a){a=a
instanceof
k?a.toString():a;j(a+": No such file or directory")}function
aD(a){return new
k(4,a,a.length)}function
ac(a){ag(b.Invalid_argument,a)}function
aj(){ac("index out of bounds")}function
an(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
al(b,a){if(a>>>0>=b.l)aj();return an(b,a)}function
q(a){if(a<0)ac("Bytes.create");return new
k(a?2:9,c,a)}function
at(a){return a.l}function
A(c){if(a.Uint8Array)var
d=new(a.Uint8Array)(c.l);else
var
d=new
Array(c.l);var
f=c.c,e=f.length,b=0;for(;b<e;b++)d[b]=f.charCodeAt(b);for(e=c.l;b<e;b++)d[b]=0;c.c=d;c.t=4;return d}function
v(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?B(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?B(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)A(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aa(){}function
d(a){this.data=a}d.prototype=new
aa();d.prototype.truncate=function(a){var
b=this.data;this.data=q(a|0);v(b,0,this.data,0,a)};d.prototype.length=function(){return at(this.data)};d.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=q(b+a),f=this.data;this.data=e;v(f,0,this.data,0,c)}v(d,g,this.data,b,a);return 0};d.prototype.read=function(c,a,d,b){var
e=this.length();v(this.data,c,a,d,b);return 0};d.prototype.read_one=function(a){return al(this.data,a)};d.prototype.close=function(){};d.prototype.constructor=d;function
g(b,a){this.content={};this.root=b;this.lookupFun=a}g.prototype.nm=function(a){return this.root+a};g.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(e(this.root),e(a));if(b!==0)this.content[a]=new
d(b[1])}};g.prototype.exists=function(a){if(a==c)return 1;var
d=a+n,e=new
RegExp(y+d);for(var
b
in
this.content)if(b.match(e))return 1;this.lookup(a);return this.content[a]?1:0};g.prototype.readdir=function(d){var
g=d==c?c:d+n,h=new
RegExp(y+g+J),e={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;b.push(a[1])}}return b};g.prototype.is_dir=function(a){var
e=a==c?c:a+n,f=new
RegExp(y+e+J),g=[];for(var
d
in
this.content){var
b=d.match(f);if(b)return 1}return 0};g.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};g.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+L);if(b.text&&b.binary)j(this.nm(a)+$);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+G);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
d(q(0));return this.content[a]}else
aA(this.nm(a))};g.prototype.register=function(b,a){if(this.content[b])j(this.nm(b)+G);if(a
instanceof
k)this.content[b]=new
d(a);else
if(a
instanceof
Array)this.content[b]=new
d(aD(a));else
if(a.toString){var
c=e(a.toString());this.content[b]=new
d(c)}};g.prototype.constructor=g;function
ab(a){if(a.t!=4)A(a);return a.c}function
ao(a,c,b){b&=0xff;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}A(a)}a.c[c]=b;return 0}function
am(b,a,c){if(a>>>0>=b.l)aj();return ao(b,a,c)}var
z=a.Buffer;function
m(a){this.fs=require("fs");this.fd=a}m.prototype=new
aa();m.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};m.prototype.length=function(){return this.fs.fstatSync(this.fd).size};m.prototype.write=function(g,c,d,f){var
b=ab(c);if(!(b
instanceof
a.Uint8Array))b=new(a.Uint8Array)(b);var
e=z.from(b);this.fs.writeSync(this.fd,e,d,f,g);return 0};m.prototype.read=function(h,e,d,g){var
b=ab(e);if(!(b
instanceof
a.Uint8Array))b=new(a.Uint8Array)(b);var
f=z.from(b);this.fs.readSync(this.fd,f,d,g,h);for(var
c=0;c<g;c++)am(e,d+c,f[d+c]);return 0};m.prototype.read_one=function(d){var
c=new(a.Uint8Array)(1),b=z.from(c);this.fs.readSync(this.fd,b,0,1,d);return b[0]};m.prototype.close=function(){this.fs.closeSync(this.fd)};m.prototype.constructor=m;function
l(a){this.fs=require("fs");this.root=a}l.prototype.nm=function(a){return this.root+a};l.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};l.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};l.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};l.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};l.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
m(d)};l.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};l.prototype.constructor=l;var
r=t.match(/[^\/]*\//)[0];function
aI(){return typeof
a.process!=="undefined"&&typeof
a.process.versions!=="undefined"&&typeof
a.process.versions.node!=="undefined"}var
u=[];if(aI())u.push({path:r,device:new
l(r)});else
u.push({path:r,device:new
g(r)});u.push({path:r+P,device:new
g(r+P)});function
aM(b){var
f=as(b),b=f.join(n),e=b+n,c;for(var
d=0;d<u.length;d++){var
a=u[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
ax(a){return a.l}function
ai(d,f){var
a=o[d],c=e(f),b=ax(c);a.file.write(a.offset,c,0,b);a.offset+=b;return 0}function
aJ(b){var
c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stderr.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.error&&d.error(b)}}function
aK(b){var
c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stdout.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.log&&d.log(b)}}function
w(d,f,e,a){if(b.fds===undefined)b.fds=new
Array();a=a?a:{};var
c={};c.file=e;c.offset=a.append?e.length():0;c.flags=a;c.output=f;b.fds[d]=c;if(!b.fd_last_idx||d>b.fd_last_idx)b.fd_last_idx=d;return d}function
aN(d,c,h){var
a={};while(c){switch(c[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}c=c[2]}if(a.rdonly&&a.wronly)j(d.toString()+L);if(a.text&&a.binary)j(d.toString()+$);var
e=aM(d),f=e.device.open(e.rest,a),g=b.fd_last_idx?b.fd_last_idx:0;return w(g+1,ai,f,a)}w(0,ai,new
d(q(0)));w(1,aK,new
d(q(0)));w(2,aJ,new
d(q(0)));function
av(d){var
c=b.fds[d];if(c.flags.wronly)j(S+d+" is writeonly");var
a={file:c.file,offset:c.offset,fd:d,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
ae(e){var
d=b.fds[e];if(d.flags.rdonly)j(S+e+" is readonly");var
a={file:d.file,offset:d.offset,fd:e,opened:true,out:true,buffer:c};o[a.fd]=a;return a.fd}function
aw(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
h(d,e,c){if(c&&a.toplevelReloc)d=a.toplevelReloc(c);b[d+1]=e;if(c)b[c]=e}function
ah(a){return a}function
aG(f){for(var
g=c,b=g,a,j,d=0,h=f.length;d<h;d++){a=f.charCodeAt(d);if(a<i){for(var
e=d+1;e<h&&(a=f.charCodeAt(e))<i;e++);if(e-d>I){b.substr(0,1);g+=b;b=c;g+=f.slice(d,e)}else
b+=f.slice(d,e);if(e==h)break;d=e}if(a<Z){b+=String.fromCharCode(0xc0|a>>6);b+=String.fromCharCode(i|a&p)}else
if(a<0xd800||a>=F)b+=String.fromCharCode(H|a>>12,i|a>>6&p,i|a&p);else
if(a>=0xdbff||d+1==h||(j=f.charCodeAt(d+1))<T||j>F)b+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-0x35fdc00;b+=String.fromCharCode(M|a>>18,i|a>>12&p,i|a>>6&p,i|a&p)}if(b.length>s){b.substr(0,1);g+=b;b=c}}return g+b}function
ar(a){var
b=9;if(!ad(a))b=8,a=aG(a);return new
k(b,a,a.length)}var
ay={};function
af(a){return ay[a]}function
aH(c){if(c
instanceof
Array)return c;if(a.RangeError&&c
instanceof
a.RangeError&&c.message&&c.message.match(/maximum call stack/i))return ah(b.Stack_overflow);if(a.InternalError&&c
instanceof
a.InternalError&&c.message&&c.message.match(/too much recursion/i))return ah(b.Stack_overflow);if(c
instanceof
a.Error&&af(Y))return[0,af(Y),c];return[0,b.Failure,ar(String(c))]}var
C=[f,e(N),-2];h(11,[f,e(K),-12],K);h(10,[f,e(E),-11],E);h(9,[f,e(R),-10],R);h(8,[f,e(V),-9],V);h(7,[f,e(Q),-8],Q);h(6,[f,e(U),-7],U);h(5,[f,e(O),-6],O);h(4,[f,e(X),-5],X);h(3,[f,e(_),-4],_);h(2,[f,e(W),-3],W);h(1,C,N);h(0,[f,e(D),-1],D);aq(0);av(0);ae(1);ae(2);function
ak(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{au(d)}catch(a){a=aH(a);if(a[1]!==C)throw a}var
a=c;continue}return 0}}ak(aw(0));return}(function(){return this}()));
